### ISSUE TITLE
I would like a "development" mode that doesn't persist to DB

### ISSUE THREAD

**Issue by balaclark** [domharrington/database-updates#3]
It would streamline development of more complex scripts.

**Comment by domharrington** [comment]
Sort of like a dry run? or outputting what will be affected? Wondering if we can use `db.collection.explain()` or something? Do you have any thoughts?

**Comment by balaclark** [comment]
It would be more like just allowing you to run the same script more than once, so not so much a dry run (although that would be cool).

I can achieve what I want by emitting the `done` callback and letting the script hang / or `process.exit()` so that it is not persisted.  

``` js
module.exports = function (db, done) {
  db.collection('contract').find({}).each(function (err, contract) {
    console.log(contract)
    process.exit()
  })
}
```

**Comment by domharrington** [comment]
Yup, this is often what i do when the script is more complicated than an index creation. Can you propose an improved solution for what you want?

**Comment by balaclark** [comment]
I'm not sure its worth changing anything, not invoking the callback and doing a `process.exit()` does basically what I need at this point.

**Comment by domharrington** [comment]
I think it's a good idea and would be good, but i can't think of a way that would be any more helpful than what you're doing.
