### ISSUE TITLE
es6 update breaks older node version

### ISSUE THREAD

**Issue by balaclark** [domharrington/database-updates#4]
Hey Dom! 

https://github.com/domharrington/database-updates/commit/21d457d883e3d87d92991ad9c0d6a04cf603af46 should have warranted a major version bump as npm will silently upgrade this package to 1.2.0 if ~1.0.0 was installed. This has broken a few older projects that don't support es6.

**Comment by domharrington** [comment]
Hey Bala! I hope you're doing well?

I think it must've been this one actually: https://github.com/domharrington/database-updates/commit/2e4e5415cc0b573c4088e2ff2f9ed259e20182a2 that's where I upgraded to use arrow functions. What error are you getting?

**Comment by balaclark** [comment]
Hey, sorry I missed your response. I'm good! Heard you've gone all american now?

Can't remember the actual error message, but it is because arrow functions etc. don't work on node 0.10. As this was a minor update any project that has a dep of `^1.0.0` will get upgraded to it and it then breaks. Also, as this is normally a dev dep it doesn't get shrinkwrapped.

**Comment by domharrington** [comment]
Yeah i moved here in November! How's things in the UK?

You're right... sorry for the mess up there, my bad. I know it's not gunna help you much now but i just released 2.0.0 and deprecated 1.2.0
